### ISSUE TITLE
Failed to activate the minimap-find-and-replace package

### ISSUE THREAD

**Issue by kishore-vk** [atom-minimap/minimap-find-and-replace#23] opened 2017-05-30 05:47 UTC
TypeError: Cannot read property 'metadata' of undefined
    at Object.activatePlugin (file:///C:/Users/user_name/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace.coffee:26:68)
    at Main.activatePlugin (C:\Users\user_name\.atom\packages\minimap\lib\mixins\plugin-management.js:187:12)
    at Main.updatesPluginActivationState (C:\Users\user_name\.atom\packages\minimap\lib\mixins\plugin-management.js:171:14)
    at pluginsSubscriptions.(anonymous function).add.atom.config.observe (C:\Users\user_name\.atom\packages\minimap\lib\mixins\plugin-management.js:241:12)
    at Config.module.exports.Config.observeKeyPath (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\src\config.js:625:1)
    at Config.module.exports.Config.observe (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\src\config.js:150:1)
    at Main.registerPluginControls (C:\Users\user_name\.atom\packages\minimap\lib\mixins\plugin-management.js:240:53)
    at Main.registerPlugin (C:\Users\user_name\.atom\packages\minimap\lib\mixins\plugin-management.js:83:12)
    at Object.consumeMinimapServiceV1 (file:///C:/Users/user_name/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace.coffee:15:14)
    at Provider.module.exports.Provider.provide (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\node_modules\service-hub\lib\provider.js:34:1)
    at ServiceHub.module.exports.ServiceHub.consume (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\node_modules\service-hub\lib\service-hub.js:50:1)
    at Package.module.exports.Package.activateServices (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\src\package.js:454:1)
    at Package.module.exports.Package.activateNow (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\src\package.js:256:1)
    at C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\src\package.js:225:1
    at Package.module.exports.Package.measure (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\src\package.js:99:1)
    at C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\src\package.js:218:1
    at Package.module.exports.Package.activate (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\src\package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\src\package-manager.js:642:1)
    at C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\node_modules\settings-view\lib\package-manager.js:519:1
    at exit (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\node_modules\settings-view\lib\package-manager.js:128:1)
    at triggerExitCallback (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\src\buffered-process.js:338:1)
    at ChildProcess.<anonymous> (C:\Users\user_name\AppData\Local\atom\app-1.17.2\resources\app\src\buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)

**Comment by thekyriarchy** [comment] 2018-05-13 18:36
I just got this error as well, using Fedora 28

**Comment by UziTech** [comment] 2020-11-19 16:11
duplicate of #16

**Closed by UziTech** 2020-11-19 16:11 UTC
